# 1. 라이브러리 설치

In [4]:
# !pip install pandas

In [5]:
import pandas as pd

# 2. 판다스 실습

In [6]:
# Series 사용하기
a1 = pd.Series([1,2,3,4])

In [7]:
a1

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
# 타입 확인하기
type(a1)

pandas.Series

#### Series의 합을 구하고 싶은 경우 : sum()

In [9]:
a1.sum()

np.int64(10)

#### 평균을 구하고싶은 경우 : mean()

In [10]:
a1.mean()

np.float64(2.5)

#### 인덱스 명칭 변경 : index

In [12]:
a3 = pd.Series(['이름', '나이', '성별', '직업'])
a3

0    이름
1    나이
2    성별
3    직업
dtype: str

In [13]:
a3_1 = pd.Series(
    ['이름', '나이', '성별', '직업'],
    index=['id1', 'id2', 'id3', 'id4'],
    name='회원정보'
)
a3_1

id1    이름
id2    나이
id3    성별
id4    직업
Name: 회원정보, dtype: str

#### Series Dic형태 데이터 구조

In [16]:
a4 = pd.Series(
    {'name':'홍길동','age':22, 'gender':'M', 'job':'AI개발자'},
    name="회원정보"
)
a4

name        홍길동
age          22
gender        M
job       AI개발자
Name: 회원정보, dtype: object

In [18]:
a4['name']

'홍길동'

In [19]:
a4 == '홍길동'

name       True
age       False
gender    False
job       False
Name: 회원정보, dtype: bool

In [20]:
a4[a4=='홍길동']

name    홍길동
Name: 회원정보, dtype: object

#### 슬라이싱 처리하는 방법

In [21]:
a5 = pd.Series(['이름', '나이', '성별', '직업'])

In [22]:
a5[1]

'나이'

In [23]:
a5[2:]

2    성별
3    직업
dtype: str

In [24]:
a5[::-1] # 역순 reverse

3    직업
2    성별
1    나이
0    이름
dtype: str

# 3. DataFrame 사용법

In [25]:
df1 = pd.DataFrame([1,2,3,4])
df1

   0
0  1
1  2
2  3
3  4

In [27]:
df2 = pd.DataFrame([
    ['A제품', '2025-05-26', '입고', 5000],
    ['B제품', '2025-05-26', '입고', 3000],
    ['C제품', '2025-05-26', '출고', 4000],
    ['D제품', '2025-05-26', '입고', 2000],
    ['E제품', '2025-05-26', '입고', 1000],
],
columns=['제목','생산일자','입출고','금액']
)
df2

    제목        생산일자 입출고    금액
0  A제품  2025-05-26  입고  5000
1  B제품  2025-05-26  입고  3000
2  C제품  2025-05-26  출고  4000
3  D제품  2025-05-26  입고  2000
4  E제품  2025-05-26  입고  1000

In [28]:
df2['금액']

0    5000
1    3000
2    4000
3    2000
4    1000
Name: 금액, dtype: int64

In [30]:
df2['제목']

0    A제품
1    B제품
2    C제품
3    D제품
4    E제품
Name: 제목, dtype: str

In [31]:
df2['금액'].sum()

np.int64(15000)

In [32]:
df2[['생산일자','금액']]

         생산일자    금액
0  2025-05-26  5000
1  2025-05-26  3000
2  2025-05-26  4000
3  2025-05-26  2000
4  2025-05-26  1000

# 4. Mart 데이터 70만건 Pandas 처리 실습

In [34]:
# 마트 데이터 불러오기
df_mart = pd.read_csv('./df1_exam.csv')

In [35]:
df_mart

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [36]:
df_mart.head(1)

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04

In [37]:
df_mart.info()

<class 'pandas.DataFrame'>
RangeIndex: 705571 entries, 0 to 705570
Data columns (total 20 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   공급일자      705571 non-null  str
 1   요일        705571 non-null  str
 2   공급월       705571 non-null  int64
 3   공급주차      705571 non-null  int64
 4   회원번호      705571 non-null  int64
 5   조합원상태     705571 non-null  str
 6   물품대분류     705571 non-null  str
 7   물품중분류     705571 non-null  str
 8   물품소분류     705571 non-null  str
 9   물품명       705571 non-null  str
 10  구매수량      705571 non-null  float64
 11  주소-구      705571 non-null  str
 12  주소-동      705571 non-null  str
 13  성별        705566 non-null  str
 14  연령        705538 non-null  float64
 15  연령대       705538 non-null  str
 16  구매금액      705571 non-null  int64
 17  구매매장      705571 non-null  str
 18  반품_원거래일자  11234 non-null   float64
 19  구매시각      705571 non-null  str
dtypes: float64(3), int64(4), str(13)
memory usage: 107.7 MB

In [38]:
df_mart.describe()

,공급월,공급주차,회원번호,구매수량,연령,구매금액,반품_원거래일자
count,705571.000000,705571.000000,7.055710e+05,705571.000000,705538.000000,7.055710e+05,1.123400e+04
mean,3.510817,13.500022,7.390639e+08,1.138203,50.756234,1.092004e+04,2.018034e+07
std,1.719153,7.517818,4.251288e+08,0.754448,11.418854,1.670323e+04,5.229237e+02
min,1.000000,1.000000,1.876416e+07,-50.000000,1.000000,-6.662160e+05,2.017121e+07
25%,2.000000,7.000000,3.906917e+08,1.000000,42.000000,4.116000e+03,2.018021e+07
50%,4.000000,13.000000,7.456573e+08,1.000000,49.000000,7.275000e+03,2.018040e+07
75%,5.000000,20.000000,1.045186e+09,1.000000,58.000000,1.263500e+04,2.018052e+07
max,6.000000,26.000000,1.670621e+09,50.000000,108.000000,2.751014e+06,2.018063e+07

In [ ]:
df_mart.isnull() # 데이터가 있으면 False, null 이면 True

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
705567,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
705568,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
705569,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
705570,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
df_mart.isnull().sum() # column에서 null의 개수를 확인할 수 있음

공급일자             0
요일               0
공급월              0
공급주차             0
회원번호             0
조합원상태            0
물품대분류            0
물품중분류            0
물품소분류            0
물품명              0
구매수량             0
주소-구             0
주소-동             0
성별               5
연령              33
연령대             33
구매금액             0
구매매장             0
반품_원거래일자    694337
구매시각             0
dtype: int64

In [41]:
df_mart.columns

Index(['공급일자', '요일', '공급월', '공급주차', '회원번호', '조합원상태', '물품대분류', '물품중분류', '물품소분류',
       '물품명', '구매수량', '주소-구', '주소-동', '성별', '연령', '연령대', '구매금액', '구매매장',
       '반품_원거래일자', '구매시각'],
      dtype='str')

In [42]:
df_mart['구매금액'].sum()

np.int64(7704862190)

In [43]:
df_mart['구매금액'].describe()

count    7.055710e+05
mean     1.092004e+04
std      1.670323e+04
min     -6.662160e+05
25%      4.116000e+03
50%      7.275000e+03
75%      1.263500e+04
max      2.751014e+06
Name: 구매금액, dtype: float64

In [44]:
df_mart.index

RangeIndex(start=0, stop=705571, step=1)

In [45]:
df_mart.values

array([['2018-01-02', '화', 1, ..., '매장C', nan, '10:04'],
       ['2018-01-02', '화', 1, ..., '매장C', nan, '10:05'],
       ['2018-01-02', '화', 1, ..., '매장C', nan, '10:05'],
       ...,
       ['2018-06-30', '토', 6, ..., '매장A', nan, '14:37'],
       ['2018-06-30', '토', 6, ..., '매장A', nan, '18:04'],
       ['2018-06-30', '토', 6, ..., '매장A', nan, '16:36']],
      shape=(705571, 20), dtype=object)

In [46]:
df_mart.iloc[-1]

공급일자             2018-06-30
요일                        토
공급월                       6
공급주차                     26
회원번호              301961920
조합원상태                  정상회원
물품대분류                    음료
물품중분류                    음료
물품소분류                    빙과
물품명         포도꽁꽁(120ml)/매장용
구매수량                    1.0
주소-구                    수지구
주소-동                   풍덕천동
성별                        여
연령                     49.0
연령대                     40대
구매금액                   1914
구매매장                    매장A
반품_원거래일자                NaN
구매시각                  16:36
Name: 705570, dtype: object

In [47]:
df_mart.iloc[:10]

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
5,2018-01-02,화,1,1,716128320,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,51.0,50대,7083,매장C,NaN,10:10
6,2018-01-02,화,1,1,743192512,정상회원,채소,과일채소,딸기,딸기/(500g),1.0,수지구,성복동,여,51.0,50대,17038,매장C,NaN,10:12
7,2018-01-02,화,1,1,743192512,정상회원,채소,잎/줄기채소,어린잎채소,어린잎채소(100g),2.0,수지구,성복동,여,51.0,50대,11104,매장C,NaN,10:12
8,2018-01-02,화,1,1,743192512,정상회원,채소,양념채소,생강,생강(300g),1.0,수지구,성복동,여,51.0,50대,7083,매장C,NaN,10:12
9,2018-01-02,화,1,1,743192512,정상회원,채소,쌈채소류,쌈케일,쌈케일(150g),1.0,수지구,성복동,여,51.0,50대,2584,매장C,NaN,10:12

In [ ]:
df_mart.shape # numpy 타입만 가능

(705571, 20)

In [49]:
# 정렬(오름차순)
df_mart.sort_values(by='구매금액')

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
157876,2018-02-09,금,2,6,1529962048,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-4.0,수지구,풍덕천동,남,29.0,30대이하,-666216,매장C,20180206.0,16:59
181579,2018-02-14,수,2,7,747242304,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-4.0,수지구,신봉동,여,54.0,50대,-666216,매장C,20180206.0,14:06
145272,2018-02-06,화,2,6,1031186176,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,풍덕천동,여,51.0,50대,-499662,매장C,20180206.0,16:04
144210,2018-02-06,화,2,6,747242304,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,신봉동,여,54.0,50대,-499662,매장C,20180206.0,16:42
142077,2018-02-06,화,2,6,307284928,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,풍덕천동,여,53.0,50대,-499662,매장C,20180206.0,18:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585654,2018-06-01,금,6,22,153723200,정상회원,채소,버섯,상황버섯,린테우스상황버섯(200g/유),5.0,수지구,동천동,여,52.0,50대,1445383,매장A,NaN,18:13
155255,2018-02-09,금,2,6,236805184,정상회원,건강,건강일반,건강/기타,홍삼/도라지절편모음(각 20g*5개),17.0,수지구,상현동,여,39.0,30대이하,1448255,매장B,NaN,12:17
127674,2018-02-02,금,2,5,938963392,정상회원,간식,과자,한과/유과,한과모음3(1.2kg),20.0,수지구,상현동,여,40.0,40대,1588964,매장B,NaN,16:22
208148,2018-02-23,금,2,8,742461248,정상회원,양념/가루,장,메주,메주(1말:약6-7kg:솔뫼),9.0,분당구,정자동,남,106.0,70대이상,1688514,매장D,NaN,11:30
182163,2018-02-14,수,2,7,854303808,정상회원,채소,뿌리채소,산양삼,산양삼/7년근이상(5주),6.0,수지구,풍덕천동,여,52.0,50대,2751014,매장B,NaN,12:36

In [ ]:
# 정렬(내림차순)
df_mart.sort_values(by='구매금액', ascending=False)

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
182163,2018-02-14,수,2,7,854303808,정상회원,채소,뿌리채소,산양삼,산양삼/7년근이상(5주),6.0,수지구,풍덕천동,여,52.0,50대,2751014,매장B,NaN,12:36
208148,2018-02-23,금,2,8,742461248,정상회원,양념/가루,장,메주,메주(1말:약6-7kg:솔뫼),9.0,분당구,정자동,남,106.0,70대이상,1688514,매장D,NaN,11:30
127674,2018-02-02,금,2,5,938963392,정상회원,간식,과자,한과/유과,한과모음3(1.2kg),20.0,수지구,상현동,여,40.0,40대,1588964,매장B,NaN,16:22
155255,2018-02-09,금,2,6,236805184,정상회원,건강,건강일반,건강/기타,홍삼/도라지절편모음(각 20g*5개),17.0,수지구,상현동,여,39.0,30대이하,1448255,매장B,NaN,12:17
585654,2018-06-01,금,6,22,153723200,정상회원,채소,버섯,상황버섯,린테우스상황버섯(200g/유),5.0,수지구,동천동,여,52.0,50대,1445383,매장A,NaN,18:13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680788,2018-06-25,월,6,26,153886528,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,풍덕천동,여,52.0,50대,-499662,매장A,20180625.0,11:11
144210,2018-02-06,화,2,6,747242304,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,신봉동,여,54.0,50대,-499662,매장C,20180206.0,16:42
142077,2018-02-06,화,2,6,307284928,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-3.0,수지구,풍덕천동,여,53.0,50대,-499662,매장C,20180206.0,18:52
157876,2018-02-09,금,2,6,1529962048,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-4.0,수지구,풍덕천동,남,29.0,30대이하,-666216,매장C,20180206.0,16:59
181579,2018-02-14,수,2,7,747242304,정상회원,건강,건강일반,추출/농축액,흑염소진액(100ml*30봉),-4.0,수지구,신봉동,여,54.0,50대,-666216,매장C,20180206.0,14:06

In [51]:
# 구매수량과 연령대가 낮은 상위 10개
df_mart.sort_values(by=['구매수량','연령'], ascending=[False,True]).iloc[:10]

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
382065,2018-04-09,월,4,15,1230917760,정상회원,수산,소금,가공소금,볶은왕소금(500g),50.0,기타,기타,남,43.0,40대,162725,매장C,NaN,17:45
386251,2018-04-09,월,4,15,1230917760,정상회원,반찬,절임/장아찌,절임,무쌈(300g),50.0,기타,기타,남,43.0,40대,191441,매장C,NaN,17:45
664021,2018-06-21,목,6,25,86983296,정상회원,채소,잎/줄기채소,깻잎,깻잎(30장),50.0,수지구,풍덕천동,여,51.0,50대,90935,매장A,NaN,17:22
665064,2018-06-21,목,6,25,86983296,정상회원,채소,콩나물,숙주나물,숙주나물(300g),50.0,수지구,풍덕천동,여,51.0,50대,201014,매장A,NaN,17:22
665065,2018-06-21,목,6,25,86983296,정상회원,채소,열매채소,풋고추,풋고추(150g),50.0,수지구,풍덕천동,여,51.0,50대,114865,매장A,NaN,17:22
665636,2018-06-21,목,6,25,86983296,정상회원,채소,버섯,팽이버섯,팽이버섯(150g),50.0,수지구,풍덕천동,여,51.0,50대,57432,매장A,NaN,17:22
607549,2018-06-06,수,6,23,548171456,정상회원,축산물,유제품,요구르트,블루베리요구르트(120ml),43.0,수지구,풍덕천동,여,52.0,50대,98784,매장C,NaN,10:35
659553,2018-06-20,수,6,25,157158656,정상회원,채소,열매채소,오이,오이(5개),40.0,수지구,신봉동,여,50.0,50대,168468,매장D,NaN,12:23
276072,2018-03-12,월,3,11,595068864,정상회원,양념/가루,가루,양념가루,카레(매운맛: 100g),40.0,수지구,신봉동,여,53.0,50대,206757,매장D,NaN,11:39
277720,2018-03-12,월,3,11,595068864,정상회원,양념/가루,가루,양념가루,카레(순한맛:100g),40.0,수지구,신봉동,여,53.0,50대,206757,매장D,NaN,11:39

In [52]:
df_mart['연령대'].value_counts()

연령대
40대      270573
50대      174458
30대이하    106392
60대       95019
70대이상     59096
Name: count, dtype: int64

In [53]:
df_mart['연령대'] == '40대'

0          True
1         False
2         False
3         False
4         False
          ...
705566    False
705567    False
705568    False
705569     True
705570     True
Name: 연령대, Length: 705571, dtype: bool

In [57]:
age_40 = (df_mart['연령대'] == '40대')
age_40

0          True
1         False
2         False
3         False
4         False
          ...
705566    False
705567    False
705568    False
705569     True
705570     True
Name: 연령대, Length: 705571, dtype: bool

In [58]:
df_mart.loc[age_40] # 40대만 추출

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
17,2018-01-02,화,1,1,1049686784,정상회원,간식,식사대용,식사대용/기타,닭고기볶음밥(300g),1.0,수지구,풍덕천동,여,40.0,40대,5743,매장C,NaN,10:31
18,2018-01-02,화,1,1,164510272,정상회원,채소,양념채소,양파,양파(2kg),1.0,수지구,풍덕천동,여,42.0,40대,8711,매장C,NaN,10:32
19,2018-01-02,화,1,1,1185171072,정상회원,양념/가루,가루,양념가루,카레(순한맛:100g),1.0,수지구,풍덕천동,여,47.0,40대,5169,매장C,NaN,10:37
20,2018-01-02,화,1,1,1206815744,정상회원,채소,양념채소,대파,대파(700g),1.0,수지구,풍덕천동,여,42.0,40대,5265,매장C,NaN,10:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705556,2018-06-30,토,6,26,572193664,정상회원,반찬,두부/유부,콩가공/기타,콩국물(300g),1.0,수지구,풍덕천동,여,46.0,40대,2202,매장A,NaN,13:48
705560,2018-06-30,토,6,26,1333795840,정상회원,반찬,밑반찬,김가공,김부각(50g),1.0,수지구,풍덕천동,여,41.0,40대,7275,매장A,NaN,15:28
705561,2018-06-30,토,6,26,1333795840,정상회원,채소,잎/줄기채소,브로컬리,브로컬리(250g),1.0,수지구,풍덕천동,여,41.0,40대,3982,매장A,NaN,15:28
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [ ]:
# 특정 데이터만 추출하는 방법, 한줄로 처리
df_mart.loc[df_mart['연령대'] == '40대']

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),1.0,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04
17,2018-01-02,화,1,1,1049686784,정상회원,간식,식사대용,식사대용/기타,닭고기볶음밥(300g),1.0,수지구,풍덕천동,여,40.0,40대,5743,매장C,NaN,10:31
18,2018-01-02,화,1,1,164510272,정상회원,채소,양념채소,양파,양파(2kg),1.0,수지구,풍덕천동,여,42.0,40대,8711,매장C,NaN,10:32
19,2018-01-02,화,1,1,1185171072,정상회원,양념/가루,가루,양념가루,카레(순한맛:100g),1.0,수지구,풍덕천동,여,47.0,40대,5169,매장C,NaN,10:37
20,2018-01-02,화,1,1,1206815744,정상회원,채소,양념채소,대파,대파(700g),1.0,수지구,풍덕천동,여,42.0,40대,5265,매장C,NaN,10:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705556,2018-06-30,토,6,26,572193664,정상회원,반찬,두부/유부,콩가공/기타,콩국물(300g),1.0,수지구,풍덕천동,여,46.0,40대,2202,매장A,NaN,13:48
705560,2018-06-30,토,6,26,1333795840,정상회원,반찬,밑반찬,김가공,김부각(50g),1.0,수지구,풍덕천동,여,41.0,40대,7275,매장A,NaN,15:28
705561,2018-06-30,토,6,26,1333795840,정상회원,채소,잎/줄기채소,브로컬리,브로컬리(250g),1.0,수지구,풍덕천동,여,41.0,40대,3982,매장A,NaN,15:28
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),1.0,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,1.0,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36

In [60]:
# 40대를 제외하고 추출하는 함수.
df_mart.loc[df_mart['연령대'] != '40대']

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),1.0,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),1.0,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,1.0,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09
5,2018-01-02,화,1,1,716128320,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),1.0,수지구,풍덕천동,여,51.0,50대,7083,매장C,NaN,10:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705564,2018-06-30,토,6,26,1278913920,정상회원,수산,해조,김,구운김밥김(10장),1.0,수지구,동천동,여,39.0,30대이하,3446,매장A,NaN,16:43
705565,2018-06-30,토,6,26,867143616,정상회원,간식,빵,"케이크,롤,선물",플레인롤케이크(90g/조각롤),-1.0,기타,기타,여,60.0,60대,-6126,매장A,20180630.0,15:54
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),1.0,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),1.0,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),2.0,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37

In [61]:
# 40대이면서 남성인 데이터만 추출.
df_mart.loc[(df_mart['연령대'] == '40대') & (df_mart['성별']=='남')]

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,구매수량,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각
34,2018-01-02,화,1,1,570500992,정상회원,간식,떡,즉석떡,절편(170g),1.0,수지구,풍덕천동,남,47.0,40대,3829,매장C,NaN,11:19
38,2018-01-02,화,1,1,1314239168,정상회원,간식,과자,스낵,밥풀과자(120g),4.0,수지구,성복동,남,48.0,40대,20676,매장C,NaN,11:22
196,2018-01-02,화,1,1,850970432,정상회원,채소,뿌리채소,당근,당근(1kg),1.0,기흥구,보정동,남,45.0,40대,4786,매장C,NaN,17:11
197,2018-01-02,화,1,1,850970432,정상회원,축산물,알,유정란,동물복지유정란(10알/국내산),1.0,기흥구,보정동,남,45.0,40대,6892,매장C,NaN,17:11
328,2018-01-02,화,1,1,1090633856,탈퇴,채소,잎/줄기채소,시금치,시금치(300g),1.0,수지구,신봉동,남,41.0,40대,4403,매장D,NaN,17:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705197,2018-06-30,토,6,26,273041728,정상회원,반찬,즉석조리,간편요리,잡채(300g),1.0,수지구,풍덕천동,남,44.0,40대,9668,매장C,NaN,13:53
705258,2018-06-30,토,6,26,163435648,정상회원,수산,수산가공,젓갈/액젓,새우육젓(250g),1.0,수지구,풍덕천동,남,49.0,40대,26802,매장C,NaN,17:20
705334,2018-06-30,토,6,26,408947328,정상회원,축산물,소,한우(냉장),한우채끝(안심대안/200g/신선육),1.0,기타,기타,남,46.0,40대,23739,매장D,NaN,12:31
705335,2018-06-30,토,6,26,408947328,정상회원,반찬,두부/유부,두부,두부(1모:420g),1.0,기타,기타,남,46.0,40대,3733,매장D,NaN,12:31
705542,2018-06-30,토,6,26,932214976,정상회원,간식,빵,"식빵, 식사대용",쌀로만든잉글리쉬머핀(66g×4개)/매장,1.0,기타,기타,남,41.0,40대,7466,매장A,NaN,11:36

In [62]:
# 컬럼 정보를 리스트로 가져오기
df_mart.describe().columns.tolist()

['공급월', '공급주차', '회원번호', '구매수량', '연령', '구매금액', '반품_원거래일자']

In [63]:
# 문자형데이터는 모두 제거 하는 경우
total_list = df_mart.columns.tolist()
total_list

['공급일자',
 '요일',
 '공급월',
 '공급주차',
 '회원번호',
 '조합원상태',
 '물품대분류',
 '물품중분류',
 '물품소분류',
 '물품명',
 '구매수량',
 '주소-구',
 '주소-동',
 '성별',
 '연령',
 '연령대',
 '구매금액',
 '구매매장',
 '반품_원거래일자',
 '구매시각']

In [64]:
#  문자정보를 뽑아낸것
num_list = df_mart.describe().columns.tolist()
tmp_list = list(set(total_list) - set(num_list))
df_mart[tmp_list]

,물품소분류,요일,물품대분류,조합원상태,주소-구,물품중분류,주소-동,성별,물품명,구매시각,연령대,공급일자,구매매장
0,사과,화,과실,정상회원,수지구,과일,풍덕천동,여,사과/유(1.5kg),10:04,40대,2018-01-02,매장C
1,느타리버섯,화,채소,정상회원,수지구,버섯,풍덕천동,여,느타리버섯(300g),10:05,30대이하,2018-01-02,매장C
2,유정란,화,축산물,정상회원,수지구,알,풍덕천동,여,유정란/매장용(10알/국내산),10:05,30대이하,2018-01-02,매장C
3,두부,화,반찬,정상회원,수지구,두부/유부,풍덕천동,여,연두부(100g),10:08,30대이하,2018-01-02,매장C
4,"식빵, 식사대용",화,간식,정상회원,수지구,빵,풍덕천동,여,아침빵(240g/8개)/매장,10:09,30대이하,2018-01-02,매장C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,멸치류,토,수산,정상회원,수지구,건어물,성복동,여,국물멸치(300g),17:56,50대,2018-06-30,매장A
705567,미역/다시마,토,수산,정상회원,수지구,해조,동천동,여,자른다시마(100g),14:37,60대,2018-06-30,매장A
705568,두부,토,반찬,정상회원,수지구,두부/유부,동천동,여,두부(1모:420g),14:37,60대,2018-06-30,매장A
705569,스낵,토,간식,정상회원,수지구,과자,동천동,여,하늘바다새우(60g),18:04,40대,2018-06-30,매장A
705570,빙과,토,음료,정상회원,수지구,음료,풍덕천동,여,포도꽁꽁(120ml)/매장용,16:36,40대,2018-06-30,매장A

In [65]:
# 숫자를 뽑아내고 싶은 경우
df_mart[df_mart.describe().columns.tolist()]

        공급월  공급주차        회원번호  구매수량    연령   구매금액  반품_원거래일자
0         1     1   272369856   1.0  45.0  22207       NaN
1         1     1  1506656256   1.0  36.0   4977       NaN
2         1     1  1506656256   1.0  36.0   7083       NaN
3         1     1  1023108864   1.0  36.0    766       NaN
4         1     1  1476143616   1.0  34.0   4403       NaN
...     ...   ...         ...   ...   ...    ...       ...
705566    6    26   146297344   1.0  51.0   9189       NaN
705567    6    26  1532985472   1.0  63.0   5169       NaN
705568    6    26  1532985472   2.0  63.0   7466       NaN
705569    6    26  1209779776   1.0  41.0   3542       NaN
705570    6    26   301961920   1.0  49.0   1914       NaN

[705571 rows x 7 columns]

In [66]:
df_mart['공급일자_dt'] = pd.to_datetime(df_mart['공급일자'])

In [67]:
df_mart

,공급일자,요일,공급월,공급주차,회원번호,조합원상태,물품대분류,물품중분류,물품소분류,물품명,...,주소-구,주소-동,성별,연령,연령대,구매금액,구매매장,반품_원거래일자,구매시각,공급일자_dt
0,2018-01-02,화,1,1,272369856,정상회원,과실,과일,사과,사과/유(1.5kg),...,수지구,풍덕천동,여,45.0,40대,22207,매장C,NaN,10:04,2018-01-02
1,2018-01-02,화,1,1,1506656256,정상회원,채소,버섯,느타리버섯,느타리버섯(300g),...,수지구,풍덕천동,여,36.0,30대이하,4977,매장C,NaN,10:05,2018-01-02
2,2018-01-02,화,1,1,1506656256,정상회원,축산물,알,유정란,유정란/매장용(10알/국내산),...,수지구,풍덕천동,여,36.0,30대이하,7083,매장C,NaN,10:05,2018-01-02
3,2018-01-02,화,1,1,1023108864,정상회원,반찬,두부/유부,두부,연두부(100g),...,수지구,풍덕천동,여,36.0,30대이하,766,매장C,NaN,10:08,2018-01-02
4,2018-01-02,화,1,1,1476143616,정상회원,간식,빵,"식빵, 식사대용",아침빵(240g/8개)/매장,...,수지구,풍덕천동,여,34.0,30대이하,4403,매장C,NaN,10:09,2018-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705566,2018-06-30,토,6,26,146297344,정상회원,수산,건어물,멸치류,국물멸치(300g),...,수지구,성복동,여,51.0,50대,9189,매장A,NaN,17:56,2018-06-30
705567,2018-06-30,토,6,26,1532985472,정상회원,수산,해조,미역/다시마,자른다시마(100g),...,수지구,동천동,여,63.0,60대,5169,매장A,NaN,14:37,2018-06-30
705568,2018-06-30,토,6,26,1532985472,정상회원,반찬,두부/유부,두부,두부(1모:420g),...,수지구,동천동,여,63.0,60대,7466,매장A,NaN,14:37,2018-06-30
705569,2018-06-30,토,6,26,1209779776,정상회원,간식,과자,스낵,하늘바다새우(60g),...,수지구,동천동,여,41.0,40대,3542,매장A,NaN,18:04,2018-06-30
705570,2018-06-30,토,6,26,301961920,정상회원,음료,음료,빙과,포도꽁꽁(120ml)/매장용,...,수지구,풍덕천동,여,49.0,40대,1914,매장A,NaN,16:36,2018-06-30

In [68]:
df_mart['공급일자_dt'].dt.year

0         2018
1         2018
2         2018
3         2018
4         2018
          ...
705566    2018
705567    2018
705568    2018
705569    2018
705570    2018
Name: 공급일자_dt, Length: 705571, dtype: int32